# Meta
description: 魔法使いの手帳
keywords: programming, javascript, ReactJS, hexo, photograph, gunpla
site_desc: 第三外部記録装置
profile_image: /images/profile.png
version: 0.1

# Navigation
navigation:
- name: Home
	slug: home
	icon: home
	url: /
- name: Archives
	slug: archives
	icon: archive
	url: /archives

# Search
search: 
	enable: true
	service: google # google/hexo/algolia/azure/baidu
	# google 
	google_api_key: AIzaSyCio5FIUM888ByRdQlfvlOMzcKBcVRhHzc
	google_engine_id: 009006483223214840080:haexrqo6rl0
	# algolia
	algolia_app_id:
	algolia_api_key:
	algolia_index_name:
	# azure
	azure_service_name:
	azure_index_name:
	azure_query_key:
	# baidu
	baidu_api_id:

# Miscellaneous
google_analytics: UA-99998080-1
favicon: /images/favicon.png
author_url: http://rakugaki.me

# Less
less:
	compress: true

# use url, not username
social:
- slug: email
	icon: envelope
	url: mailto:slavikshen@gmail.com
- slug: github
	icon: github
	url: https://github.com/slavikshen
- slug: twitter
	icon: twitter
	url: https://twitter.com/slavikshen
- slug: rss
	icon: rss
	url: /atom.xml
- slug: facebook
	url: # https://www.facebook.com/slavikshen
- slug: linkedin
	url: # https://www.linkedin.com/in/slavikshen
